### ISSUE TITLE
Bug in OData mock server?

### ISSUE THREAD

**Issue by haimat** [SAP/cloud-s4-sdk-book#2]
After downloading the OData mock server and installing it [as described here](https://sap.github.io/cloud-s4-sdk-book/pages/mock-odata.html), I wanted to start the server locally on my machine.  This leads to the following error:

    /Development/Projects/business-partner-mock/odata-helpers.js:26
    const handleEntityNavPropertiesForExpand = function(entity, expandedProperties = []) {
                                                                                   ^

    SyntaxError: Unexpected token =
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Development/Projects/business-partner-mock/business-partner/business-partner-api.js:5:15)
        at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)

Any ideas what could be the problem here?

**Comment by sacnl** [comment]
Which version of Node.js are you running? (Type `node --version` in a command line shell.)
The default parameters used here are only available in Node.js 6 or higher. See https://stackoverflow.com/questions/35463985/default-parameters-in-node-js for more details.

**Comment by haimat** [comment]
After upgrading Node.js to version 6 the mock server is running fine now.
Thanks!
