### ISSUE TITLE
[Mock Server] TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by haimat** [SAP/cloud-s4-sdk-book#3]
The mock server and the first version of the business partner application both launch fine. However, calling the `/api/business-partners` endpoint of my application leads to the following error in the mock server:

    Request: GET /sap/opu/odata/sap/API_BUSINESS_PARTNER/$metadata
    Serving metadata for Business Partner API
    Request: GET /sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner?$filter=BusinessPartnerCategory%20eq%20'1'&$orderby=LastName%20asc&$select=BusinessPartner,FirstName,LastName&$format=json
    Reading business partner entity set
    TypeError: Object.entries is not a function
        at handleEntityNavPropertiesForExpand (/Development/Projects/business-partner-mock/odata-helpers.js:27:19)
        at entityArray.map (/Development/Projects/business-partner-mock/odata-helpers.js:65:39)
        at Array.map (native)
        at handleEntitySetNavPropertiesForExpand (/Development/Projects/business-partner-mock/odata-helpers.js:65:24)
        at expand (/Development/Projects/business-partner-mock/odata-helpers.js:145:13)
        at Layer.handle [as handle_request] (/Development/Projects/business-partner-mock/node_modules/express/lib/router/layer.js:95:5)
        at next (/Development/Projects/business-partner-mock/node_modules/express/lib/router/route.js:137:13)
        at retrieveAllBusinessPartners (/Development/Projects/business-partner-mock/business-partner/business-partner-api.js:11:5)
        at Layer.handle [as handle_request] (/Development/Projects/business-partner-mock/node_modules/express/lib/router/layer.js:95:5)
        at next (/Development/Projects/business-partner-mock/node_modules/express/lib/router/route.js:137:13)

Am not a Node.js expert at all -
Any ideas what could be the problem here?

**Comment by sacnl** [comment]
Sorry, I should have been more specific in the previous issue: actually, the mock server requires Node.js 8.x, as mentioned in the prerequisites of the [setup guide](https://sap.github.io/cloud-s4-sdk-book/pages/mock-odata.html).

**Comment by haimat** [comment]
Yes, thanks, that worked!
